### ISSUE TITLE
ability to set a base GP

### ISSUE THREAD

**Issue by PathlessGiant** [Alumian/CEPGP#10]
fiddling around in the cepgp.lua I was able to make it so our guild could use a base GP that was higher than 1 so that you would need to come to a few raids before your priority was over 1.0

Would it be possible to add it in to this new options menu you've built? amazing work btw! :)

setting a custom number that nobody can decay below and when resetting all EPGP standings, it defaults to 0,X where X is custom number chosen by the guild

**Comment by Alumian** [comment]
Hi PathlessGiant,
Sorry for the delayed response. It came through at about 3am and I was like nope ima sleep.

So essentially you just want an option to be able to set the initial GP of each player? And they should not be able to go below that number even when decayed is that right?

Thanks,
Alumian.

**Comment by PathlessGiant** [comment]
Ye that is correct. :) changing the 'zero' GP value, EP should always decay back to 0 and start at 0.

**Comment by Alumian** [comment]
There you go, feature added :)
If you find any more issues or have any other requests just let me know.

**Comment by Alumian** [comment]
Hi PathlessGiant,
Please be aware that I forgot to add the default GP to saved variables in version 1.3.0. I have pushed version 1.3.1 now and that should have fixed the issue.
