### ISSUE TITLE
Standby list

### ISSUE THREAD

**Issue by PathlessGiant** [Alumian/CEPGP#11]
quality of life request. :)

would it be difficult to add a standby function like other modern epgp addons. as an example, people could whisper the raid leader, "!standby" and they would be entered into a list that the raid leader could manage in the addon interface(removing/adding people to the list/adjusting % modifier). anyone on the list when the raid receives EP will also receive that amount of EP.

another suggestion could be to add the ability to control a %% modifier on the list's EP, for example if the raid receives 10 EP for killing the boss, you could set it so the standby receives 80% of that, so they instead receive 8 EP automatically.

I feel like it is a big ask, so no need to rush or break your back. we're super impressed with your addon so far and continue to recommend it everyone we meet. 👍

**Comment by Alumian** [comment]
Sounds like a good idea, it is a bit of a task but I think it's worth putting in. I'll look into it :)

**Comment by Alumian** [comment]
So I've been thinking about this, and my only issue is that if the person who will be awarding the EP essentially gets kicked off the game by any means, whether that be relogging, game crash, disconnection, alt-F4 or anything really, then the standby list will be cleared and you'll have to repopulate the list all over again.

Alternatively I could make it more automatic which would eliminate that problem. Such that, I could make it say like, all of [elected guild rank] (raiders, for example) who are currently online and not in the raid group will be awarded x% of EP awards.

Thoughts?

**Comment by PathlessGiant** [comment]
Sounds even better man, a lot more elegant.

**Comment by Alumian** [comment]
Okay sure thing. That sounds much easier to implement. I'll try to have it up and running early next week :)
Just got a little bit of work I need to get done before I can resume on the addon.

**Comment by Alumian** [comment]
Hey PathlessGiant,
I managed to squeeze some time in to get some dev work done. I hope you're happy with the implementation that I've arrived at. Unfortunately I'm really only able to test it by myself by multiboxing clients at the moment so I haven't performed extensive testing. At this stage it appears to be working as intended, but please let me know if you find any issues.
Thanks!

**Comment by PathlessGiant** [comment]
Amazing news man, any bugs we find I'll be sure to let you know! Thanks for putting in the time.

**Comment by PathlessGiant** [comment]
Seems to be working great so far :)
