### ISSUE TITLE
Auto award EP on boss kill settings don't persist between relogs

### ISSUE THREAD

**Issue by ruscur** [Alumian/CEPGP#15]
The settings for which bosses give automatic EP awards don't persist after logging out.  They should save to SavedVariables or something (I don't know much about addons) so they don't have to be set every time.

**Comment by Alumian** [comment]
Hi Ruscur,
Just to confirm, you are pressing apply on the same page as setting the EP values, right? Each apply button only saves the values on their respective page.
Come to think of it, I might change that.
But yes, there is a saved variable already in place for the EP values.

Please confirm that you are pressing the right button and get back to me.

Thanks,
Alumian

**Comment by Alumian** [comment]
Nevermind - I have just checked it myself and I can see there is an issue. I'll get working on a fix.

**Comment by ruscur** [comment]
Only the button on the GP settings works, the boss settings button doesn't.

**Comment by Alumian** [comment]
Thanks for bringing this to my attention. I have found the issue and will push an update in a moment to resolve it. I had already written saved variables previously for this, but my function to check the variable was malfunctioning.
