### ISSUE TITLE
EPGP export

### ISSUE THREAD

**Issue by ruscur** [Alumian/CEPGP#16]
It would be cool to have every EPGP standing in the guild to save to SavedVariables so that 

 - it can be backed up somewhere in case someone messes up the officer notes, or there's an addon bug
 - it would be possible to whip up some magic such that EPGP standings are uploaded to a guild website or discord server etc

Not sure how much of a pain it would be, or if there's a limit to how much crap you can put in SavedVariables, but just putting something in there that could be parsed after a raid would be useful.  Probably turned off by default.

**Comment by Alumian** [comment]
Unfortunately addons lack i/o capacity and thus they cannot write a "backup" file per se, however I do have an idea on how I can make this work.
It is a major feature so it will take some time and I likely won't prioritise this unless I don't have anything else to do. But not a bad suggestion.

**Comment by PathlessGiant** [comment]
https://webdkp.com/images/screenshots/player.jpg

think he means something like this

**Comment by Alumian** [comment]
Yeah, so the only way that the addon can dump data is via saved variables and unfortunately I'm unable to manipulate the saved variable in such a way which would allow you to upload the data to another platform. That would require an additional client to accompany the addon.
However, I can implement local backups, and by extension of that, there is a _chance_ (don't get excited) that I could implement a comprehensive raid log of what you see in that screenshot. I'm not promising anything, but it's doable.

**Comment by ruscur** [comment]
Just having a local backup would be fine, others can build whatever they want on top of that

 I think triggering it manually is fine

**Comment by PathlessGiant** [comment]
Triggers when you close client?

**Comment by Alumian** [comment]
I was thinking that, but the problem with automated backups if to conserve space you really only want 1 backup per day and when it's automated, what happens if it backs up after the error has been made?

**Comment by PathlessGiant** [comment]
Yeahh :( unless it knew to not save info from the same raid ID twice

**Comment by Alumian** [comment]
Okay I need clarification. Do you guys want the addon to backup the entire guild EPGP standings or are you looking for a log of EPGP movement and loot distribution in a raid (like the screenshot you posted)?

**Comment by PathlessGiant** [comment]
Do what you feel is best :) was just trying to be helpful, not sure what ruscur is looking for. This add-on is great! I will let you guys talk about it

**Comment by Alumian** [comment]
No worries, I appreciate both of your ideas lol, I just need to know what you guys are looking for because both of these paths are major functions and I don't want to get it wrong lol.

**Comment by ruscur** [comment]
If you only log changes and you lose a previous backup, then the information isn't that useful.  Loot distribution and movement isn't too hard to get from other sources (i.e. people logging to legacy-logs.com) so personally I would only be interested in full standings

**Comment by Alumian** [comment]
Hi guys,
Please note that this feature has been added in version 1.6.0.

Thanks,
Alumian.
