### ISSUE TITLE
Investigate hiding offline guild members

### ISSUE THREAD

**Issue by ruscur** [Alumian/CEPGP#17]
Vanilla API limitations require that offline guild members need to always be visible in order to get information about them (i.e. EPGP in officer notes).  Investigate to see if there's a way around it, even if only for "viewers" (people without edit permissions that wouldn't be running decays, for example).

**Comment by Alumian** [comment]
Hi Ruscur,
I have found a workaround for showing offline guild members. The addon should now fully operate even when offline guild members are not shown.
Please let me know if you find any bugs in this new functionality.

Thanks,
Alumian.

**Comment by ruscur** [comment]
Awesome! I'll try it out
