### ISSUE TITLE
Option for addon communication over whispers

### ISSUE THREAD

**Issue by ruscur** [Alumian/CEPGP#18]
The `!info` class of commands communicate the result over the addon channel to prevent disconnects or anti-spam measures punishing the player running the addon.  It would be nice if there was an option to do this over whispers so other players didn't have to run the addon to get this functionality.

Personally I play on a small server with a handful of raiding guilds where a) actual spammers are very obvious due to population size and b) staff could easily whitelist the loot masters of the few guilds, so anti-spam measures aren't a problem.

**Comment by Alumian** [comment]
Hi Ruscur,
I have decided that adding an option for this seems redundant. Instead, I've added functionality such that if a player has the addon installed, then the addon channel will be used, if they don't, then they will be whispered.
I will push an update shortly with this adjustment.
