### ISSUE TITLE
Miss looting

### ISSUE THREAD

**Issue by Cigarzz** [Alumian/CEPGP#23]
The addon is occasionally distributing loot to the incorrect players. its random works fine for a bit but then completely sends loot to the wrong selected recipient. using the give for GP button.

Have no way of contacting you except through here alumian

**Comment by Alumian** [comment]
Hi Cigarzz,
Is the issue still occurring?

**Comment by Alumian** [comment]
No response from Cigarzz. I'm going to put this down as conflict from external addons or a server bug as this issue has not been reported by anyone else.

**Comment by Spigoe** [comment]
I have had this issue occur three times, twice during the same raid.
It gives the items to people not on the list, i.e. they haven't whispered "!need".

**Comment by Alumian** [comment]
Hi Spigoe,
Could you please provide a list of add-ons that you were running at the time?

Thanks

**Comment by Spigoe** [comment]
Extended QuestLog 3.6.1
_LazyPig
Action Bar Saver
AdvancedTradeSkillWindow
Atlas
AtlasLoot Enchanced
AtlasQuest
aux
BeanCounter
BetterAlign
BetterCharacterStats
BG Enemy Frames
BigWigs Classic-WoW
Bongos
Bongos_ActionBar
Bongos_Options
Cartographer
ccwatch
Character Status Compare
Classic EPGP
cyCircled
DPSMate
EnhTooltip
EquipCompare
EzPoison
FuBar - BagFu
FuBar - ClockFu
FuBar - DuraTek
FuBar - LocationFu
FuBar - MoneyFU
FuBar - PerformanceFu
FuBar 2.0
HonorSpy
Improved Error Frame
Informant
KLHThreatMeter
Luna Unit Frames
Macro Tooltips (Vanilla)
Mail
MobHealth3
MobHealrth3: Blizzard Frames
MoveAnything!
MPOWA
OmniCC
Outfitter
PicoPoisons
Prat
Prat_Fubar2
StatCompareBuff
StatCompareCharactor
StatCompareSets v 1.7.001
StatCompareSpell
StatCompareUI v 1.7.001
Stubby
SuperMacro
ShaguPlates
Shagutooltips
Questie v3.7.0

**Comment by Alumian** [comment]
Thanks Spigoe,
Do you know if the people that are incorrectly receiving loot received loot before distributing the current item?

**Comment by Alumian** [comment]
Hi Spigoe,
I have pushed an update to my [beta branch](https://github.com/Alumian/CEPGP/tree/beta). Unfortunately, I am currently not active on any classic servers and as such, have no means to test this fix. Please post back if the issue persists. If there are no updates on this issue in 1 month then I will assume that the issue has been resolved.
If the issue does persists, please advise me of the following:
- Did the recipient receive loot prior to the bug occurring?
- Does it continue to occur continuously after it starts occurring?
- Any other pattern that you notice or information you feel could be useful in diagnosing this issue.

Thanks

**Comment by Spigoe** [comment]
Hi,
One had recieved loot before, two had not.

**Comment by Spigoe** [comment]
To follow up. Our next raid is Sunday, if the issue persists after your update I'll be able to give you more details.

**Comment by Alumian** [comment]
Hi Spigoe,
Did the issue occur on your raid on Sunday?

**Comment by Spigoe** [comment]
It happened once, then we swapped to handing it out "manually".
I right clicked the loot in the loot window as you do when doing master loot without an addon, then I used CEPGP to hand out the piece and it went to the wrong person.

**Comment by Alumian** [comment]
Hi Spigoe,
Could you please confirm if the issue still occurs with the beta build?

Thanks

**Comment by Alumian** [comment]
As there has been no response from either Spigoe or Cigarzz, I will assume the update to the beta branch has resolved this issue.
