### ISSUE TITLE
Available in WoW Classic?

### ISSUE THREAD

**Issue by ArthurBane** [Alumian/CEPGP#26]
Hey brother!

My guildies and I have been relying on your addon for loot distribution on a vanilla server for a while now. We feel like it would be really difficult to use anything else because it handles all our community quirks so much better than anything else available. So first of all, thank you for creating it!

You've probably heard that Blizzard has announced WoW Classic and will be revealing a release date at BlizzCon at the start of November. It sounds like there'll be a playable build for anyone with virtual tickets too, so I think they're going to beta test it early next year.

A majority of my guildies have been pretty open about leaving our server for the Classic beta when it hits and we'd really like to stay together and form a new guild... and this addon has been a godsend in resolving every edge case issue we've had about drops which would otherwise blow up into a full guild split (I've seen it happen too man times bro). So I'm wondering if we'll be able to use this addon in Classic? Or if it'll be possible to modify it somewhat to work in Classic?

Even looking at what's available for retail at the moment, this addon is far much more competently designed. Other addons work in some situations for a while, but eventually someone feels the system is unfair and then you have to work around the system to accommodate special requests and you lose track of that stuff and everyone who remembers is unhappy. Not with this addon, it just works and then bends over backward to let us do loot distribution the way we want.

I'm really hoping there's a way to use your addon in Classic. It would really make a massive difference in the raid experience of a lot of people and settle so many disputes before they start. Again, that you so much for making this for vanilla. Let me know what the prospects are for it being transferrable to Classic.

**Comment by Alumian** [comment]
Hi ArthurBane,

Thanks for your question. I'm really glad that my addon has proven so useful to your guild! In terms of the availability for my addon in the new release of Classic WoW, the short answer is, unfortunately I'm just not sure at this point. I can guarantee that the new implementation will not be running the same API and I'm not sure what kind of changes I'll be up against. At this stage, I'm not currently playing WoW so I didn't really have any plans of developing the addon further.
When used with the modern API I imagine that the addon should still work, but I can't guarantee that. Also it would probably run pretty inefficiently since I've kind of made up some functions to replicate functions in the modern API.
Since I don't currently have a subscription / don't plan on getting one any time soon, any fixes I apply would be untested. I'm happy for you to test it if you'd like and if there are any issues that seem simple enough I can apply a fix for them.
Let me know what your thoughts are.

Thanks,
Alumian

**Comment by ArthurBane** [comment]
"Useful" is completely underselling it brother. I feel like you really _get_ nuanced guild dynamics and built your addon around what guilds actually _need_ rather than what one person wants for all guilds (like most other addons). It's hard to describe but a lot of other addons that do a similar job _just don't get it_ and fall down in the most critical areas.

I completely understand if you can't make any major revisions because you're taking a break from WoW. I have an off and on relationship with WoW so I've taken so many breaks. For me it's usually a social thing, either there's a big guild blowout (something your addon has really helped prevent!) or there's something important happening in real life where I decide to give up playing WoW to focus on that... I usually end up regretting time off because it removes a lot of structure from my life that actually levels me out. But when I'm taking a break I need to be on that break until I just get that feeling that I'm ready to jump back in, so I totally get being on break.

I'd be happy to do some testing to get this addon to work in Classic. I'm not sure how to do that, but I'm ready to learn me some addon testing. I hope nothing major will need to be done because I'd really like to continue using this addon in Classic. I really appreciate you offering to make fixes. Lots of addons get completely abandoned when the author takes a break. You're a real solid guy Alumian 👍

**Comment by Alumian** [comment]
Haha Thanks! Alright so I've given this some thought and what I've arrived at is, I'll close this ticket for now and if you'd like to, when classic wow comes out just keep using the addon and submit a ticket whenever you find a bug. If I do come back to WoW (honestly, not very likely), then I'll more actively look into rewriting my addon to work with the modern API. But unfortunately, at this point the only means I have to go off for future development are the tickets submitted here.

If you have any further questions or would like to discuss this matter with me further, go ahead and add me on Discord. My ID is Alumian#6465.

Thanks,
Alumian

**Comment by Alumian** [comment]
Hi Arthur,
Not sure if you're still subscribed to this thread or not but if you are, I just wanted to let you know that your question was asked again and I've revised my answer. If you're still interested, check out the thread here: https://github.com/Alumian/CEPGP/issues/29 for my updated answer.

Thanks,
Alumian
