### ISSUE TITLE
CEPGP Save Standings

### ISSUE THREAD

**Issue by stunny99** [Alumian/CEPGP#28]
Hello.

I use your addon on Kronos 3 private server. It works wonderfully. However, whenever I try to use the Save Standing button (which i suspect exports the info somewhere) I am unable to find where that info goes. The readme does not have any information regarding this.

Thank you for any clarity.

**Comment by Alumian** [comment]
Hi Stunny99,

Thanks for your question and my apologies for the poor documentation on this matter. The save standings function actually dumps the logs into your saved variables file. So once you save a log, you'll need to refresh your UI, logout or exit the game to commit those changes and then you'll be able to view the logs in saved variables. I hope this helps.

**Comment by Andrioden** [comment]
For those that wonder, you can find the saved standings data in

C:\Program Files (x86)\World of Warcraft\_classic_\WTF\Account\CHARNAME\SavedVariables\CEPGP.bak

@Alumian - my suggestion is to document this.

**Comment by Alumian** [comment]
@Andrioden if you have a feature request, submit it in a new ticket in the correct repository. Thanks.
