### ISSUE TITLE
Remove EP from an individual member or the raid

### ISSUE THREAD

**Issue by TheGreekOne** [Alumian/CEPGP#32]
I want to be able to remove EP from an individual for poor performance or other reasons.  I would like to be able to remove it from the whole raid as well.

**Comment by Alumian** [comment]
Hi TheGreekOne, please see the latest version which I just uploaded with your feature request implemented.

**Comment by TheGreekOne** [comment]
TY!

**Comment by TheGreekOne** [comment]
So to remove EP do I just put a negative amount?

**Comment by Alumian** [comment]
Yep that's correct.
