### ISSUE TITLE
[Bug] No menu buttons work in WoW Classic

### ISSUE THREAD

**Issue by Andrioden** [Alumian/CEPGP#33]
Here is what i do:
1. Log in
2. Addon enabled /cep gives addon help output
3. Run /cep show
4. No buttons (Guild, Raid, or X close) button works

Details
- Playing on WoW Classic stress test.
- Not getting any error message.
- Not getting anything from /cep debug.

**Comment by Alumian** [comment]
Hey Adrioden,

What version of the add-on are you running?

**Comment by Alumian** [comment]
I just realised what repo this is. This is the wrong add-on for the retail classic. Go to GitHub.com/Alumian/CEPGP-Retail for the correct version.

**Comment by Andrioden** [comment]
Thanks for an quick response, your right, seems to work now!

I got confused by the naming. I thought the retail was for wow retail and not classic.
