### ISSUE TITLE
CEPGP Default values in GP formula

### ISSUE THREAD

**Issue by stefoxy** [Alumian/CEPGP#36]
Hello thanks for showing everything, however my officers and me(GM) found that the formula might be wrong 
Because 
4,83 x (1^ ((ilvl/26)+(rarity-4)) x slot) x 1 
Will bring same results no mater what item level and rarity is the loot only the slot itself because 1^any number is 1. Which is pointless to have rarity and ilvl in their at all if this is the case. Please follow up on this because most of the formulas are having 2 instead of 1 that we get on default when installing the addon. 
Let me know if we are wrong or the addon got a bug with the latest updates and formula is not correct. Using 1.12.4

**Comment by Alumian** [comment]
Hey Stefoxy,

You're quite right. I did actually fix this previously, but unfortunately that fix will only come through for anyone who has never had the add-on installed before. You can change it on your own client and you'll be good to go but yup I did adjust the default value after I noticed haha.

Also just for future reference, this is not the correct repository lol. You're looking for CEPGP-Retail.

Thanks!
