### ISSUE TITLE
Table index is nil

### ISSUE THREAD

**Issue by Believe82** [Alumian/CEPGP#5]
When I logged in to addon I get "CEPGP.lua:87:table index is nil"
I ask if this is an error that occurs just before the first raid or is it a recurring error.

Thanks for all the help

**Comment by PathlessGiant** [comment]
Not sure if its because of that but I get the error as well.

**Comment by Alumian** [comment]
Hi guys, very sorry for not getting back to you sooner - I kinda went MIA from private servers for a few months.
Are you still getting the issue? Can you please provide more details on how I might be able to replicate the issue? I'm not able to replicate it on my end.

Thanks,
Alumian.

**Comment by Alumian** [comment]
Hi guys,
I was able to replicate the issue just now. I have made adjustments to the code which should have fixed it. Please download the new version.

Thanks,
Alumian
