### ISSUE TITLE
Some items do not have a GP value

### ISSUE THREAD

**Issue by PathlessGiant** [Alumian/CEPGP#6]
some items have a value of 0, is this easy to fix?

**Comment by PathlessGiant** [comment]
ahh its just some tiny errors inside CEPGP_index.lua easy fix :)

**Comment by Alumian** [comment]
Hi PathlessGiant,
I'm very sorry for not getting back to you sooner, I went MIA for a little while and forgot about my project. Could you please let me know what item(s) didn't have an entry in the index? I'll add them in or make adjustments to make them read better. I have seen some variance across different servers in terms of item names which I'm planning on adding support for.

Thanks,
Alumian.
