### ISSUE TITLE
loot assignment spam when looting non boss npcs

### ISSUE THREAD

**Issue by PathlessGiant** [Alumian/CEPGP#9]
there is a weird bug when looting things in the raid such as hourglass sand, fiery core, etc - seems to be anything and everything that doesn't drop off a boss.

it says in the raid chat that the last item that was given out via the addon, has now been given to x person for free over and over every time you loot something off a mob that isn't a boss.

will edit post with screenshots next time i see it.

**Comment by Alumian** [comment]
Hi PathlessGiant,
Thanks for bringing that to my attention. I've just pushed an update which should fix the issue. Let me know if the issue persists.

Thanks,
Alumian.
